include:
  - project: 'library/ci'
    file:
      - 'root.gitlab-ci.yaml'
    inputs:
      merge_branch_action: delete
      gradle_builder: true
      release_version: "0.9"

variables:
  CI_DEBUG_TRACE: "true"


